// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/snet/token_service.proto

package snet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenService_GetToken_FullMethodName = "/escrow.TokenService/GetToken"
)

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// It is expected that the user would call the GetChannelState to Determine the Current state of the Channel
// Based on the usage forecast, the user/client will have to sign for an amount L + U , where L is the last amount Signed
// and U is the amount based on expected usage.
// Please be aware that the Signing up an amount upfront (Pre Paid) does come with a risk and hence the
// user must exercise caution on the amount signed specially with new service providers.
// If there is no need of making concurrent calls then you may consider pay per mode.
// Using a Token, the Client can now make concurrent calls, which was not supported previously with the pay per mode.
// However the pay per mode is a lot secure than the pre-paid mode.
type TokenServiceClient interface {
	// GetToken method checks the Signature sent and returns a Token
	// 1) The Signature is valid and has to be signed in the below format
	// "__MPE_claim_message"+MpeContractAddress+ChannelID+ChannelNonce+SignedAmount
	// Signature is to let the Service Provider make a claim
	//  2. Signed amount >= Last amount Signed.
	//     if Signed amount == Last Signed amount , then check if planned_amount < used_amount
	//     if Signed amount > Last Signed amount , then update the planned amount = Signed Amount
	//
	// GetToken method in a way behaves as a renew Token too!.
	GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenReply, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, TokenService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServiceServer is the server API for TokenService service.
// All implementations must embed UnimplementedTokenServiceServer
// for forward compatibility.
//
// It is expected that the user would call the GetChannelState to Determine the Current state of the Channel
// Based on the usage forecast, the user/client will have to sign for an amount L + U , where L is the last amount Signed
// and U is the amount based on expected usage.
// Please be aware that the Signing up an amount upfront (Pre Paid) does come with a risk and hence the
// user must exercise caution on the amount signed specially with new service providers.
// If there is no need of making concurrent calls then you may consider pay per mode.
// Using a Token, the Client can now make concurrent calls, which was not supported previously with the pay per mode.
// However the pay per mode is a lot secure than the pre-paid mode.
type TokenServiceServer interface {
	// GetToken method checks the Signature sent and returns a Token
	// 1) The Signature is valid and has to be signed in the below format
	// "__MPE_claim_message"+MpeContractAddress+ChannelID+ChannelNonce+SignedAmount
	// Signature is to let the Service Provider make a claim
	//  2. Signed amount >= Last amount Signed.
	//     if Signed amount == Last Signed amount , then check if planned_amount < used_amount
	//     if Signed amount > Last Signed amount , then update the planned amount = Signed Amount
	//
	// GetToken method in a way behaves as a renew Token too!.
	GetToken(context.Context, *TokenRequest) (*TokenReply, error)
	mustEmbedUnimplementedTokenServiceServer()
}

// UnimplementedTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenServiceServer struct{}

func (UnimplementedTokenServiceServer) GetToken(context.Context, *TokenRequest) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedTokenServiceServer) mustEmbedUnimplementedTokenServiceServer() {}
func (UnimplementedTokenServiceServer) testEmbeddedByValue()                      {}

// UnsafeTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServiceServer will
// result in compilation errors.
type UnsafeTokenServiceServer interface {
	mustEmbedUnimplementedTokenServiceServer()
}

func RegisterTokenServiceServer(s grpc.ServiceRegistrar, srv TokenServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenService_ServiceDesc, srv)
}

func _TokenService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).GetToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenService_ServiceDesc is the grpc.ServiceDesc for TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "escrow.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TokenService_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/snet/token_service.proto",
}
